### ISSUE TITLE
Did you delete version from PyPI ?

### ISSUE THREAD

**Issue by Carreau** [meshpro/meshzoo#93]
I've been scratching my head on CI failure on napari, and realise that no version of meshzoo<0.10 are available on PyPI. I was just wondering if this was purposeful.

**Comment by nschloe** [comment]
Whoops, I should have thought of that. I just uploaded 0.9.9 which should hopefully satisfy your use case.

**Comment by Carreau** [comment]
Thanks, I just wanted to make sure that was intentional deletion.

The main issue is/was that the test suite is/was trying to pin numpy to 1.19 (the oldest napari supports) and that the remaining published meshio are only numpy 1.20+ so pip was basically failing to find a satisfying requirement. 

It's the same with 0.9.9 but I think we can bump our minimal numpy requirements in the test to 1.20. 

Out of curiosity why delete and not yank ? I know yank is a pretty recent PyPI feature and have only used it once, so curious if you had bad experience with it.
