### ISSUE TITLE
unclear licensing & source code access

### ISSUE THREAD

**Issue by eudoxos** [meshpro/meshzoo#94]
I appreciate this package and have been using it for testing some mesh-related stuff, but I am a bit concerned that I don't see any license information here, and no human-readable source-code either.

When I install meshzoo via pip, the module has some binary content which is interpreted via `x21.__dex__` function, where [x21](https://pypi.org/project/x21/) is distributed binary-only. Besides wanting to look into meshzoo code as the documentation is not always complete, I have obvious security concerns about binary-only module running on my machine.

I  understand someone may not want to disclose sources for their package, yet have the conveniences of pypi as distribution platform, but then the documentation should be explicit about that.

**Comment by nschloe** [comment]
I haven't decided yet what I want to do with meshzoo. For the time being, the code is closed-source. I'll add more info in the future.
